---
include_paths:
  - 'projects/ng-in-viewport/src/**'
exclude_paths:
  - '.github/**'
  - '.husky/**'
  - '.vscode/**'
  - '.yarn/**'
  - 'docs/**'
  - 'projects/demo/**'
  - 'projects/demo-e2e/**'
  - 'projects/example/**'
  - 'projects/example-e2e/**'
  - 'scripts/**'
  - 'CODE_OF_CONDUCT.md'
  - 'CHANGELOG.md'
  - 'README.md'
