pool:
  vmImage: 'Ubuntu 16.04'

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x

steps:
- task: NodeTool@0
  inputs:
    version: $(node_version)

- script: |
    yarn install
    yarn run build:lib
    yarn run build --progress=false
    yarn run lint:lib
    yarn run lint
    yarn run test:lib --watch=false --progress=false --code-coverage=true --browsers=ChromeHeadlessNoSandbox
