version: 2

anchor_1: &defaults
  working_directory: ~/ng-in-viewport
  docker:
    - image: circleci/node:10-browsers

anchor_2: &restore_cache_defaults
  keys:
    - ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
    - ng-in-viewport-

general:
  branches:
    only:
      - master
      - develop

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_defaults
      - run: xvfb-run -a node --version
      - run: xvfb-run -a yarn --version
      - run: yarn install
      - save_cache:
          key: ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: xvfb-run -a yarn run build
