version: 2

general:
  branches:
    only:
      - develop

jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/ng-in-viewport

    steps:
      - checkout

      - restore_cache:
          keys:
          - ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
          - ng-in-viewport-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}

      - run: xvfb-run -a yarn run test:lib -- --single-run --no-progress --browser=ChromeNoSandbox
      - run: xvfb-run -a yarn run e2e:lib -- --no-progress --config=protractor-ci.conf.js

      - run: xvfb-run -a yarn run test -- --single-run --no-progress --browser=ChromeNoSandbox
      - run: xvfb-run -a yarn run e2e -- --no-progress --config=protractor-ci.conf.js
