version: 2

general:
  branches:
    only:
      - develop

jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/ng-in-viewport

    steps:
      - checkout

      - restore_cache:
          keys:
          - ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}
          - ng-in-viewport-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: ng-in-viewport-{{ .Branch }}-{{ checksum "package.json" }}

      - run: xvfb-run -a yarn run lint:lib
      - run: xvfb-run -a yarn run test:lib --progress=false --browsers=ChromeHeadlessNoSandbox

      - run: xvfb-run -a yarn run lint
      # There are no tests yet
      # - run: xvfb-run -a yarn run test --progress=false --browsers=ChromeHeadlessNoSandbox
